### ISSUE TITLE
[AMD] Fooocus with ZLUDA Issue

### ISSUE THREAD

**Issue by jdeath** [CS1o/Stable-Diffusion-Info#13]
Hi,
 Excellent guides. I used it successfully to run A1111 with ZLUDA. Trying to get fooocus working, and Step 5 is giving issues. I copy the 3 renamed dllls but then get this error:
```
Traceback (most recent call last):
  File "C:\Ai\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "C:\Ai\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\Fooocus\launch.py", line 152, in <module>
    from webui import *
  File "C:\Ai\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\Fooocus\webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "C:\Ai\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\Fooocus\modules\async_worker.py", line 3, in <module>
    from extras.inpaint_mask import generate_mask_from_image, SAMOptions
  File "C:\Ai\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\Fooocus\extras\inpaint_mask.py", line 5, in <module>
    import torch
  File "C:\Ai\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\python_embeded\lib\site-packages\torch\__init__.py", line 143, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Ai\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\python_embeded\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.
```

**Comment by CS1o** [comment]
Hey and thanks!
This error is caused when the Programm is not using the Python 3.10.11 64bit installed via the normal installer and instead uses the bad Python Version from Microsoft Store.

You can verify that by open up a cmd and type:
`Python --version`
which should return Python 3.10.11
and then type
`Where python`
This will show all Python paths. If there is a Python Path that goes into Microsoft/WindowsApps and this Path is above the AppData/Programs/Python Path then thats the issue.
The correct order should look like this:
![grafik](https://github.com/user-attachments/assets/45c5375f-73b3-4c6f-8353-47397b40cf58)


Can be fixed by uninstalling the Python from Microsoft Store via Windows Settings -> Apps -> Apps & Features.
Then reboot and install Python 3.10.11 64bit via the installer again.
If that doesn help you have to go into the Windows Environment Variables and under Path where you added Zluda and HIP lookout for a Path to the WindowsApps Python and move it below the normal Python Version like shown here:
![grafik](https://github.com/user-attachments/assets/e65295d0-1482-4b0e-9ae3-c427c17cbede)
Then reboot again.

Let me know if this fixed it.

**Comment by jdeath** [comment]
Thanks for quick reply. Did not work. I had the Windows Store version of python and uninstalled it. Then rebooted. Removed all other paths from the environment variables. Rebooted. Re-installed Python 3.10.11 64bit , then rebooted. And went through the installation from scratch. rebooted.

while installing, I did get a warning that said something like "script covert-caffe2-to-onux... which is not in path, consider adding this directory". I did that, but still does not work. I also did a force install of torch (the entire line in your readme). did not get the path error, but still did not fix it after i replaced the dll's.

I can try one more time from total scratch, but think something is messed up

**Comment by CS1o** [comment]
Okay thats strange.
Whats your GPU? Driver Version. And which HIP SDK Version did you installed?
Can you try open up a cmd and run
`pip cache purge`
then run the python 3.10.11 64bit installer again and click "modify", "next", and check "Add Python to Environment variables"
then try again.

**Comment by jdeath** [comment]
RX 6650 XT
24.12.1
SDK 6.1.2 and gfx1032  . Again, it works on A1111

Did your steps, did not work. Only have 3.10.11 on. did the cache purge and force pip and it redownloaded it fresh. 

I'll try once more completely fresh and report back. thank you for your help tonight!

**Comment by CS1o** [comment]
Okay can you try open up a cmd and run these 3 commands after each other.
`cd C:\Users\%username%\AppData\Local\Microsoft\WindowsApps`
`del python.exe`
`del python3.exe`

Then run the Python 3.10.11 64bit installer again and after its done run:
`where python`
It should only show up one Path.

Then reboot the PC and then nuke and redownload Fooocus. Important is to edit the model_management.py after the first launch is done.

**Comment by jdeath** [comment]
Deleted the files in WindowsApp. Which is weird, because I already installed them and they do not show on path.

Reinstalled python, only that version shows on path (no WindowsApp version). rebooted

Got through all the steps in readme, launch first (it downloads models), quit, then edit model_management and update dlls

Noticed the python embedded in Fooccus_win64_2-5-0 is 3.10.9, does that matter?

I guess I am stuck with directml. Thanks
![unnamed](https://github.com/user-attachments/assets/66de2941-2988-410a-9982-54e0415a6115)

**Comment by CS1o** [comment]
The python embedded Version doesnt matter in this case.
The Variables are correct.
But i see no Python 3.10.11 variables in there. Thats bad.
You need to add these two PATH entries here: (The black bar is your PC Username).
You get the Path with the `where python` command.
![grafik](https://github.com/user-attachments/assets/240ad1de-06b4-4bcc-8e24-73d749daf7fd)
Then reboot the PC and redo the setup again.

If that doesnt work let me know. I'm really interested in getting a final fix to this particular Error.
Also your not missing out by not using Fooocus. It didnt got updated since August and also only gets bug fixes and no future Model support or new Features: [Source](https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#project-status-limited-long-term-support-lts-with-bug-fixes-only)

With your GPU the best you can use in terms of performance and usability would be Forge Webui with Zluda.

**Comment by jdeath** [comment]
Those are set correctly in the system section, i shows the user section. I'll try forge. I am new to this, fooocus just gave me nice results!

**Comment by CS1o** [comment]
Oh but the Zluda and HIP path need to be in the System section as stated by my guide.
They dont belong into the user section.

**Comment by jdeath** [comment]
Ok. I'll double check tomorrow, I might have gotten it backwards!

Your directions for forge-ui zluda worked perfect. Just wish it made graphics as good as fooocus out of the box. I'll keep playing, dynamic prompt script helps and the reactor plugin is was easier than using roop-unleashed.

**Comment by jdeath** [comment]
Thanks for help. I checked everything (had path in both user and system). Anyways, Forge zluda (setup with your instructions) works great and going to stick with it.
